// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MovesDiego",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "MovesDiego",
            targets: ["AppModule"],
            bundleIdentifier: "DiegoGarcia.MovesDiego",
            teamIdentifier: "84SD3C8868",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections(),
                .microphone(purposeString: "MOVES needs microphone for voice chess commands"),
                .speechRecognition(purposeString: "MOVES uses voice to enter chess moves like \"e4\""),
                .incomingNetworkConnections()
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)